CREATE TABLE employees (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(20),
    ssn VARCHAR(11) NOT NULL,
    birth_date DATE,
    gender VARCHAR(10),
    login VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    specialization VARCHAR(20),
    contract_type VARCHAR(20),
    working_shift VARCHAR(20),
    working_situation VARCHAR(30),
    resident_name VARCHAR(150),
    street_number INT,
    predirectional VARCHAR(10),
    street_name VARCHAR(150),
    street_suffix VARCHAR(20),
    postdirectional VARCHAR(10),
    sec_address_identifier VARCHAR(50),
    city VARCHAR(100),
    state VARCHAR(50),
    zip_code VARCHAR(10),
    delivery_point VARCHAR(10),
    country VARCHAR(50),
    complement VARCHAR(150),
    active TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uk_employees_ssn (ssn),
    UNIQUE KEY uk_employees_login (login)
);

CREATE TABLE guides (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(20),
    ssn VARCHAR(11) NOT NULL,
    birth_date DATE,
    gender VARCHAR(10),
    login VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    specialization VARCHAR(20),
    contract_type VARCHAR(20),
    working_shift VARCHAR(20),
    working_situation VARCHAR(30),
    resident_name VARCHAR(150),
    street_number INT,
    predirectional VARCHAR(10),
    street_name VARCHAR(150),
    street_suffix VARCHAR(20),
    postdirectional VARCHAR(10),
    sec_address_identifier VARCHAR(50),
    city VARCHAR(100),
    state VARCHAR(50),
    zip_code VARCHAR(10),
    delivery_point VARCHAR(10),
    country VARCHAR(50),
    complement VARCHAR(150),
    active TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uk_guides_ssn (ssn),
    UNIQUE KEY uk_guides_login (login)
);

CREATE TABLE visitors (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(20),
    ssn VARCHAR(11) NOT NULL,
    birth_date DATE,
    gender VARCHAR(10),
    login VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    resident_name VARCHAR(150),
    street_number INT,
    predirectional VARCHAR(10),
    street_name VARCHAR(150),
    street_suffix VARCHAR(20),
    postdirectional VARCHAR(10),
    sec_address_identifier VARCHAR(50),
    city VARCHAR(100),
    state VARCHAR(50),
    zip_code VARCHAR(10),
    delivery_point VARCHAR(10),
    country VARCHAR(50),
    complement VARCHAR(150),
    active TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uk_visitors_ssn (ssn),
    UNIQUE KEY uk_visitors_login (login)
);

CREATE TABLE animals (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    birth_date DATE,
    death_date DATE,
    mother_id BIGINT,
    father_id BIGINT,
    gender VARCHAR(10),
    race VARCHAR(100),
    specie VARCHAR(100) NOT NULL,
    animal_class VARCHAR(20),
    extinction_warning TINYINT(1),
    active TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT fk_animals_mother FOREIGN KEY (mother_id) REFERENCES animals (id),
    CONSTRAINT fk_animals_father FOREIGN KEY (father_id) REFERENCES animals (id)
);

CREATE TABLE tours (
    id BIGINT NOT NULL AUTO_INCREMENT,
    guide_id BIGINT NOT NULL,
    tour_schedule DATETIME NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT fk_tours_guide FOREIGN KEY (guide_id) REFERENCES guides (id)
);

CREATE TABLE tour_visitors (
    tour_id BIGINT NOT NULL,
    visitor_id BIGINT NOT NULL,
    PRIMARY KEY (tour_id, visitor_id),
    CONSTRAINT fk_tour_visitors_tour FOREIGN KEY (tour_id) REFERENCES tours (id),
    CONSTRAINT fk_tour_visitors_visitor FOREIGN KEY (visitor_id) REFERENCES visitors (id)
);
